### ISSUE TITLE
Could you please add a license?

### ISSUE THREAD

**Issue by mvasilkov** [mneubrand/jsfxr#3]
Hi, if I'm not overlooking something painfully obvious, this code is missing a license. This makes lawyers cry. Which is probably a good thing, but could you please consider adding a license?

This site, made by GitHub team, may help: http://choosealicense.com/

Thanks!

**Comment by mneubrand** [comment]
It's a port of as3fxr and should be licensed under the same license (APL 2.0). I'll add the appropriate license files later today.

**Comment by mvasilkov** [comment]
Great, thank you very much.

**Comment by mneubrand** [comment]
Added the license info in README.md and LICENSE.txt
