### ISSUE TITLE
Browserify compatibility + NPM publish

### ISSUE THREAD

**Issue by gre** [mneubrand/jsfxr#4]
Hi @mneubrand ,
would you like to make jsfxr works with browserify and publish it on NPM?
Do you want me to do it?

Thanks

**Comment by mneubrand** [comment]
jsfxr was primarily developed for the js13kgames contest (http://js13kgames.com/) so I don't want to add extra size to it.

As long as the minified size stays the same (or becomes even smaller) I wouldn't mind merging a PR that makes it available on NPM but I probably won't have time to do this myself anytime soon.

**Comment by gre** [comment]
Hi thanks for the reply.

I don't think I will be able to reduce the build in size and it is not the very purpose of browserify (which adds some overhead) so I have forked jsfxr and published on Github and I will try to keep this version in sync with your repository :-)

Thanks

**Comment by mneubrand** [comment]
Sounds good to me. Updates are pretty rare anyways. I'll @mention you if one comes in. Thanks
