### ISSUE TITLE
NPM package in another branch

### ISSUE THREAD

**Issue by jdnichollsc** [mneubrand/jsfxr#6]
Hey mate

What do you think having the npm package of this cool lib in another branch? :)

Regards

**Comment by mneubrand** [comment]
I will fork of a npm branch and publish it in the next days

**Comment by jdnichollsc** [comment]
Cool, let me know to add you here! https://github.com/proyecto26/awesome-jsgames

**Comment by mneubrand** [comment]
Looks like somebody already published it on npm a long time ago by @gre: https://www.npmjs.com/package/jsfxr. No need to publish again. Closing this
